from __future__ import annotations

import argparse
import sqlite3
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from alphagen_agent.db import expression_skeleton
from alphagen_agent.engine.fast_expr import validate_fast_expr


NOW = datetime.now().isoformat()


def candidates() -> list[tuple[str, str]]:
    """Paper-inspired alpha candidates tuned to fields already active locally.

    Research hooks:
    - Kakushadze (2016), "101 Formulaic Alphas": short-horizon price-volume
      reversal and low-correlation formulaic structures.
    - Chen & Kawashima (2025/2026), "Sentiment-Aware Stock Price Prediction
      with Transformer and LLM-Generated Formulaic Alpha": combine OHLCV and
      sentiment-derived formulaic features.
    - Guo & Hauptmann (2025), "Exploring the Synergy of Quantitative Factors
      and Newsflow Representations...": blend structured factors and newsflow.
    - Glasserman & Lin (2023), "Assessing Look-Ahead Bias in Stock Return
      Predictions Generated By GPT Sentiment Analysis": sentiment signals can
      carry return information, but should be stress-tested for bias/noise.
    - Falck, Rej & Thesmar (2020), "Is Factor Momentum More than Stock
      Momentum?": last-month return effects matter; combine short mean
      reversion with medium-horizon momentum.
    - Heston, Korajczyk & Sadka (2010), "Intraday Patterns in the
      Cross-section of Stock Returns": short-term reversal relates to temporary
      liquidity imbalance; approximate with daily price-volume imbalance.
    - Kalnina & Tewou (2024/2025), "Cross-sectional Dependence in
      Idiosyncratic Volatility": separate systematic and residual volatility
      components; locally approximate with beta/unsystematic-risk/IV fields.
    """
    rows: list[tuple[str, str]] = []

    def add(theme: str, expr: str) -> None:
        rows.append((theme, expr))

    # Newsflow / sentiment + price-volume overreaction.
    add(
        "paper_v3_newsflow_reversal",
        "group_neutralize(ts_decay_linear(multiply(rank(ts_zscore(scl12_sentiment, 20)), reverse(group_rank(ts_delta(close, 5), subindustry))), 5), subindustry)",
    )
    add(
        "paper_v3_newsflow_reversal",
        "ts_decay_linear(multiply(rank(ts_delta(scl12_sentiment_fast_d1, 5)), rank(divide(volume, adv20))), 5)",
    )
    add(
        "paper_v3_newsflow_reversal",
        "group_neutralize(ts_decay_linear(add(rank(group_neutralize(mdl177_5shortsentimentfactor_dmd_supply, subindustry)), reverse(group_rank(ts_delta(close, 7), subindustry))), 7), subindustry)",
    )
    add(
        "paper_v3_newsflow_reversal",
        "ts_decay_linear(multiply(rank(ts_corr(snt_buzz_ret, returns, 40)), reverse(rank(ts_zscore(ts_sum(returns, 5), 20)))), 7)",
    )
    add(
        "paper_v3_newsflow_reversal",
        "group_neutralize(ts_decay_linear(multiply(rank(ts_zscore(snt_buzz, 20)), reverse(group_rank(ts_av_diff(close, 20), subindustry))), 5), subindustry)",
    )

    # Attention / buzz conditioned reversal: high attention often amplifies
    # temporary overreaction, so test reversal only where attention is elevated.
    add(
        "paper_v3_attention_reversal",
        "trade_when(rank(ts_zscore(snt_buzz, 20)), ts_decay_linear(reverse(group_rank(ts_delta(close, 3), subindustry)), 3), 0)",
    )
    add(
        "paper_v3_attention_reversal",
        "ts_decay_linear(multiply(reverse(group_rank(ts_delta(close, 5), subindustry)), rank(ts_zscore(scl12_buzz, 20))), 5)",
    )
    add(
        "paper_v3_attention_reversal",
        "group_neutralize(ts_decay_linear(multiply(reverse(group_rank(ts_sum(returns, 5), subindustry)), rank(ts_corr(snt_buzz, volume, 20))), 5), subindustry)",
    )
    add(
        "paper_v3_attention_reversal",
        "ts_decay_linear(multiply(rank(ts_delta(daily_equity_mood_indicator, 5)), reverse(rank(ts_delta(close, 5)))), 5)",
    )

    # Factor momentum vs stock momentum: combine short-lag mean reversion with
    # medium-window continuation, avoiding plain rank(ts_zscore(field, 63)).
    add(
        "paper_v3_factor_momentum",
        "ts_decay_linear(multiply(rank(ts_delta(close, 60)), reverse(rank(ts_delta(close, 5)))), 7)",
    )
    add(
        "paper_v3_factor_momentum",
        "group_neutralize(ts_decay_linear(subtract(rank(ts_delta(close, 60)), rank(ts_delta(close, 5))), 10), subindustry)",
    )
    add(
        "paper_v3_factor_momentum",
        "ts_decay_linear(add(rank(ts_zscore(ts_sum(returns, 60), 120)), reverse(rank(ts_zscore(ts_sum(returns, 5), 20)))), 7)",
    )
    add(
        "paper_v3_factor_momentum",
        "group_neutralize(ts_decay_linear(multiply(rank(ts_zscore(mdl53_jc5_3year, 10)), reverse(group_rank(ts_delta(close, 5), subindustry))), 5), subindustry)",
    )

    # Idiosyncratic volatility / low-risk anomaly proxy.
    add(
        "paper_v3_residual_vol",
        "ts_decay_linear(multiply(reverse(rank(ts_zscore(unsystematic_risk_last_60_days, 60))), reverse(rank(ts_delta(close, 5)))), 10)",
    )
    add(
        "paper_v3_residual_vol",
        "group_neutralize(ts_decay_linear(add(reverse(group_rank(unsystematic_risk_last_30_days, subindustry)), reverse(group_rank(implied_volatility_mean_30, subindustry))), 10), subindustry)",
    )
    add(
        "paper_v3_residual_vol",
        "ts_decay_linear(multiply(reverse(rank(ts_zscore(implied_volatility_mean_60, 63))), rank(ts_zscore(ts_sum(returns, 60), 120))), 10)",
    )
    add(
        "paper_v3_residual_vol",
        "group_neutralize(ts_decay_linear(add(reverse(group_rank(beta_last_60_days_spy, subindustry)), reverse(group_rank(unsystematic_risk_last_90_days, subindustry))), 10), subindustry)",
    )
    add(
        "paper_v3_residual_vol",
        "ts_decay_linear(multiply(reverse(rank(ts_zscore(implied_volatility_mean_skew_30, 63))), reverse(rank(ts_delta(close, 5)))), 7)",
    )

    # Daily approximation of intraday liquidity imbalance and 101-style
    # price-volume structures.
    add(
        "paper_v3_liquidity_imbalance",
        "ts_decay_linear(reverse(rank(ts_corr(rank(volume), rank(vwap), 5))), 3)",
    )
    add(
        "paper_v3_liquidity_imbalance",
        "group_neutralize(ts_decay_linear(multiply(reverse(group_rank(ts_delta(close, 5), subindustry)), rank(ts_corr(volume, returns, 20))), 5), subindustry)",
    )
    add(
        "paper_v3_liquidity_imbalance",
        "ts_decay_linear(reverse(rank(ts_corr(rank(high), rank(volume), 10))), 5)",
    )
    add(
        "paper_v3_liquidity_imbalance",
        "group_neutralize(ts_decay_linear(multiply(reverse(group_rank(ts_av_diff(close, 20), subindustry)), rank(divide(volume, adv20))), 5), subindustry)",
    )

    # Lottery / extreme-return aversion proxy: fade recent max-return spikes,
    # with IV skew variants for optionality-demand flavor.
    add(
        "paper_v3_extreme_return",
        "ts_decay_linear(reverse(rank(ts_max(returns, 20))), 10)",
    )
    add(
        "paper_v3_extreme_return",
        "group_neutralize(ts_decay_linear(reverse(group_rank(ts_max(returns, 5), subindustry)), 5), subindustry)",
    )
    add(
        "paper_v3_extreme_return",
        "ts_decay_linear(multiply(reverse(rank(ts_max(returns, 20))), reverse(rank(ts_zscore(implied_volatility_mean_skew_30, 63)))), 10)",
    )
    add(
        "paper_v3_extreme_return",
        "group_neutralize(ts_decay_linear(add(reverse(group_rank(ts_max(returns, 20), subindustry)), reverse(group_rank(implied_volatility_call_30, subindustry))), 10), subindustry)",
    )

    # Analyst revision / earnings drift: use local revision and surprise fields
    # but mix them with price confirmation or reversal legs.
    add(
        "paper_v3_revision_drift",
        "ts_decay_linear(multiply(rank(snt1_d1_earningssurprise), rank(ts_delta(close, 20))), 10)",
    )
    add(
        "paper_v3_revision_drift",
        "group_neutralize(ts_decay_linear(add(rank(snt1_d1_netearningsrevision), rank(snt1_d1_earningssurprise)), 10), subindustry)",
    )
    add(
        "paper_v3_revision_drift",
        "ts_decay_linear(multiply(rank(ts_delta(snt1_d1_netrecpercent, 20)), reverse(rank(ts_delta(close, 5)))), 7)",
    )
    add(
        "paper_v3_revision_drift",
        "group_neutralize(ts_decay_linear(multiply(rank(snt1_d1_earningsrevision), rank(ts_zscore(mdl53_jc5_3year, 10))), 10), subindustry)",
    )

    # Quality/newsflow fusion: structured quality/profitability plus sentiment
    # and low-risk overlays.
    add(
        "paper_v3_quality_news_fusion",
        "group_neutralize(ts_decay_linear(add(rank(fscore_bfl_quality), rank(fscore_profitability)), 20), subindustry)",
    )
    add(
        "paper_v3_quality_news_fusion",
        "ts_decay_linear(multiply(rank(fscore_bfl_profitability), reverse(rank(ts_zscore(implied_volatility_mean_60, 63)))), 10)",
    )
    add(
        "paper_v3_quality_news_fusion",
        "group_neutralize(ts_decay_linear(add(rank(ts_zscore(mdl53_jc5_3year, 10)), rank(group_neutralize(mdl177_5shortsentimentfactor_dmd_supply, subindustry))), 5), subindustry)",
    )
    add(
        "paper_v3_quality_news_fusion",
        "ts_decay_linear(multiply(rank(fscore_bfl_momentum), rank(ts_corr(snt_buzz_ret, returns, 40))), 10)",
    )

    return rows


def main(db_path: str, limit: int, dry_run: bool) -> None:
    con = sqlite3.connect(db_path)
    existing_exprs = {r[0] for r in con.execute("SELECT expression FROM alphas")}
    existing_skeletons = {expression_skeleton(expr) for expr in existing_exprs}

    selected: list[tuple[str, str]] = []
    seen_skeletons = set(existing_skeletons)
    for theme, expr in candidates():
        result = validate_fast_expr(expr)
        if not result.valid:
            print(f"skip_invalid [{theme}] {expr}")
            for issue in result.issues:
                print(f"  - {issue.code}: {issue.message}")
            continue
        skel = expression_skeleton(expr)
        if expr in existing_exprs or skel in seen_skeletons:
            continue
        selected.append((theme, expr))
        seen_skeletons.add(skel)
        if len(selected) >= limit:
            break

    print(f"selected={len(selected)} dry_run={dry_run}")
    for idx, (theme, expr) in enumerate(selected, start=1):
        print(f"{idx:02d} [{theme}] {expr}")

    if dry_run or not selected:
        return

    con.executemany(
        """INSERT INTO alphas (expression, strategy, llm_model, status, created_at)
           VALUES (?, 'factor_mining', ?, 'generated', ?)""",
        [(expr, theme, NOW) for theme, expr in selected],
    )
    con.commit()
    first_id = con.execute("SELECT max(id) - ? + 1 FROM alphas", (len(selected),)).fetchone()[0]
    last_id = con.execute("SELECT max(id) FROM alphas").fetchone()[0]
    print(f"inserted_ids={first_id}..{last_id}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--db", default="alphagen_agent.db")
    parser.add_argument("--limit", type=int, default=32)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    main(args.db, args.limit, args.dry_run)
